#!/bin/sh

[ -f /etc/config/tailscale ] || touch /etc/config/tailscale

if ! uci -q get tailscale.settings >/dev/null 2>&1; then
	uci -q set tailscale.settings=settings
	uci -q set tailscale.settings.service_enabled='1'
	uci -q set tailscale.settings.log_stderr='1'
	uci -q set tailscale.settings.log_stdout='1'
	uci -q set tailscale.settings.port='41641'
	uci -q set tailscale.settings.state_file='/etc/tailscale/tailscaled.state'
	uci -q set tailscale.settings.fw_mode='iptables'
	uci -q commit tailscale
fi

# Make LuCI "Save & Apply" reload tailscale settings (via /sbin/luci-reload)
if ! uci -q get ucitrack.@tailscale[0] >/dev/null 2>&1; then
	uci -q add ucitrack tailscale
	uci -q set ucitrack.@tailscale[-1].init='tailscale-settings'
	uci -q commit ucitrack
fi

# Apply /etc/config/tailscale to the node on boot
[ -x /etc/init.d/tailscale-settings ] && /etc/init.d/tailscale-settings enable

exit 0
